apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
  labels:
    app: guestbook 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - image: us.icr.io/sn-labs-dcfabio96/guestbook:v1
        imagePullPolicy: Always
        name: guestbook
        ports:
        - containerPort: 3000
          name: http
        resources:
          limits:
            cpu: 5m
          requests:
            cpu: 2m 

## kubectl apply -f deployment.yml
## kubectl port-forward deployment.apps/guestbook 3000:3000
## kubectl autoscale deployment guestbook --cpu-percent=5 --min=1 --max=10

## You can check the current status of the newly-made HorizontalPodAutoscaler, by running:
## kubectl get hpa guestbook
## Load on the app:
## kubectl run -i --tty load-generator --rm --image=busybox:1.36.0 --restart=Never -- /bin/sh -c "while sleep 0.01; do wget -q -O- <URL>; done"

## Watch load:
## kubectl get hpa guestbook --watch

## APPLY CHANGES KUBERNETES
## kubectl apply -f deployment.yml
## kubectl port-forward deployment.apps/guestbook 3000:3000

## Run the below command to see the history of deployment rollouts:
## kubectl rollout history deployment/guestbook

## Run the below command to see the details of Revision of the deployment rollout:
## kubectl rollout history deployments guestbook --revision=2

## Run the below command to get the replica sets and observe the deployment which is being used now:
## kubectl get rs


## Run the below command to undo the deploymnent and set it to Revision 1:
## kubectl rollout undo deployment/guestbook --to-revision=1
